import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          navy: 'var(--color-brand-navy)',
          orange: 'var(--color-brand-orange)',
          green: 'var(--color-brand-green)',
          darkGreen: 'var(--color-brand-dark-green)',
          mint: 'var(--color-brand-mint)',
          blue: 'var(--color-brand-blue)',
          darkBg: 'var(--color-brand-dark-bg)',
        },
        primary: {
          50:  'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        secondary: {
          50:  'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
        },
        success: 'var(--color-success)',
        danger:  'var(--color-danger)',
        warning: 'var(--color-warning)',
        info:    'var(--color-info)',
      },
      fontFamily: {
        sans:  ['var(--font-sans)'],
        title: ['var(--font-title)'],
        body:  ['var(--font-body)'],
        mono:  ['var(--font-mono)'],
      },
      fontSize: {
        'h1': ['var(--text-h1)', { lineHeight: 'var(--leading-h1)', fontWeight: '700' }],
        'h2': ['var(--text-h2)', { lineHeight: 'var(--leading-h2)', fontWeight: '700' }],
        'h3': ['var(--text-h3)', { lineHeight: 'var(--leading-h3)', fontWeight: '500' }],
        'h4': ['var(--text-h4)', { lineHeight: 'var(--leading-h4)', fontWeight: '400' }],
        'h5': ['var(--text-h5)', { lineHeight: 'var(--leading-h5)', fontWeight: '400' }],
        'h6': ['var(--text-h6)', { lineHeight: 'var(--leading-h6)', fontWeight: '400' }],
        'body-lg': ['var(--text-body-lg)', { lineHeight: 'var(--leading-body-lg)', fontWeight: '500' }],
        'body-md': ['var(--text-body-md)', { lineHeight: 'var(--leading-body-md)', fontWeight: '500' }],
        'body-sm': ['var(--text-body-sm)', { lineHeight: 'var(--leading-body-sm)', fontWeight: '400' }],
        'caption': ['var(--text-caption)', { lineHeight: 'var(--leading-caption)', fontWeight: '600' }],
        'footnote': ['var(--text-footnote)', { lineHeight: 'var(--leading-footnote)', fontWeight: '600' }],
        '2xs': ['var(--text-2xs)', { lineHeight: 'var(--leading-tight)' }],
        xs:    ['var(--text-xs)',  { lineHeight: 'var(--leading-normal)' }],
        sm:    ['var(--text-sm)',  { lineHeight: 'var(--leading-normal)' }],
        base:  ['var(--text-base)',{ lineHeight: 'var(--leading-relaxed)' }],
        lg:    ['var(--text-lg)',  { lineHeight: 'var(--leading-relaxed)' }],
        xl:    ['var(--text-xl)',  { lineHeight: 'var(--leading-snug)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-snug)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-tight)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-tight)' }],
        '5xl': ['var(--text-5xl)', { lineHeight: 'var(--leading-none)' }],
      },
      lineHeight: {
        none:    'var(--leading-none)',
        tight:   'var(--leading-tight)',
        snug:    'var(--leading-snug)',
        normal:  'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
        loose:   'var(--leading-loose)',
      },
      letterSpacing: {
        tighter: 'var(--tracking-tighter)',
        tight:   'var(--tracking-tight)',
        normal:  'var(--tracking-normal)',
        wide:    'var(--tracking-wide)',
        wider:   'var(--tracking-wider)',
      },
      borderRadius: {
        sm:   'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      backgroundColor: {
        DEFAULT: 'var(--color-bg)',
        subtle:  'var(--color-bg-subtle)',
      },
      borderColor: {
        DEFAULT: 'var(--color-border)',
      },
      textColor: {
        DEFAULT: 'var(--color-text)',
        muted:   'var(--color-text-muted)',
      },
    },
  },
  plugins: [],
};

export default config;
